### ISSUE TITLE
How to run this code on multiple GPUs??? Thanks!

### ISSUE THREAD

**Issue by ymLeiFDU** [lorenmt/maxl#1]
Simply using "nn.DataParallel(model, ...)" may not work when applied "fast_weights".

**Comment by lorenmt** [comment]
Hi,

For the generic question on PyTorch usage, I recommend that you should refer to the PyTorch community for this specific type of problem. I am sorry that I would be helpful on this issue.

Thanks.

**Comment by ymLeiFDU** [comment]
In this algorithm, it is needed to assign updated weights ('fast_weights') to the model in forward process, that is to say assign fast_weights to F.conv2d(). 
I wonder how to make F.conv2d() run on multiple GPUs? 
Thanks !
