### ISSUE TITLE
Why not optimize the gen_optimizer and main optimizer with a Interleaved style in one iteration just like the optimization of generator and discriminator in GAN?

### ISSUE THREAD

**Issue by Zhengtq** [lorenmt/maxl#3]
Why not optimize the gen_optimizer and main optimizer with a Interleaved style in one iteration just like the optimization of generator and discriminator in GAN?

**Comment by lorenmt** [comment]
Hi,

We have tried updating the multi-task network and label generation network iteratively across each batch of data. But we found to update iteratively across the entire dataset producing a better performance.

**Comment by Zhengtq** [comment]
@lorenmt Thanks for your replay.
