### ISSUE TITLE
Is the use of second derivative in the meta objective when update theta_2 really necessary? Can we achieve the similarly performance  by only using one derivative?  

### ISSUE THREAD

**Issue by Zhengtq** [lorenmt/maxl#4]

**Comment by lorenmt** [comment]
Hi,

I am not sure whether I understand your question correctly. Are you asking whether it's possible to use first derivative to approximate the second derivative? If so, yes, it's possible.

You may try to use the similar technique in DARTS (to use finite difference approximating the second derivate), I believe it would significantly boost the training speed. But I did not do any experiments based on that method. If you do, please let me know the results. 

Thanks.
Sk.

**Comment by Zhengtq** [comment]
@lorenmt Thanks for your replay, other time I will try it.

**Comment by lorenmt** [comment]
Hello, in case you are still working on meta-learning related projects, I have now updated the first-order approximation implementation of MAXL in this repo. :)

**Comment by Zhengtq** [comment]
Oh great! I am still interested in this area and I am very exited to try your new work.
