### ISSUE TITLE
Why the \theta_2 can be updated?

### ISSUE THREAD

**Issue by fuzzydeep** [lorenmt/maxl#7]
In the second phrase, after the torch.autograd.grad(create_graph=True), the train_loss1 is backward() and the \theta_2 is updated.
But why the \theta_2 can be updated?
It do not calculate the derivative of \theta_2 in the torch.autograd.grad(create_graph=True) and the train_loss1.backward() does not relate to \theta_2.
Could you please give me some advices?

**Comment by lorenmt** [comment]
Hello,

It's easier to understand from the paper Eq. 3, 4. create_graph=True represents that we keep track of the gradients through another future back-prop. We use gen_optimiser to update which only includes parameters of theta_2.

**Comment by lorenmt** [comment]
If you are not familiar with gradient-based meta learning, I would suggest to look at some tutorials on MAML or DARTS.

**Comment by fuzzydeep** [comment]
您好，可能我的英语不是很好，请允许我用中文来表述一下。
其实我看了MAML之后我注意到了您的文章，发现您的文章的思路太美妙了，充分发挥了MAML的特点又青出于蓝。
但是我不是很明白，在公式4中，虽然出现了\theta_2，但是您并没有对\theta_2求导，而是对\theta_1求导。而且autograde并不会对\theta_2求梯度。那么即使create_graph，公式三和公式四都没有显示的对\theta_2求导。那\theta_2的梯度哪里来的呢？

**Comment by lorenmt** [comment]
Eq 2. 是 argmin_theta_1才是对 theta_1 求导; Eq 3. 是argmin theta_2 是对theta_2求导? Eq 4. 是对 Eq 3.里的 theta_1+的展开.

**Comment by lorenmt** [comment]
或者你参看 Algorithm 1里的写法.  注意 = 是计算 <- 才是更新.

**Comment by fuzzydeep** [comment]
我明白您的意思，这里真的挺神奇的。
比如说在代码里，更新\theta_2时（:=第二步），您是loss1.backward(),loss1其实这个计算图里并没有\theta_2。那么按照代码的意思，计算图里的\theta_2其实是来自于上一步：torch.autograd.grad(loss1+loss2, \theta_1, create_graph=True)。
我其实是这里比较困惑，loss1+loss2对\theta_1求梯度，这一步建立计算图的时候必然是有\theta_2的。所以到了第二步，才能在计算图中计算\theta_2的梯度。
不知道我的理解对吗？

**Comment by lorenmt** [comment]
正确.  计算theta_2来自 loss2 因为forward pass里用到了 label generator. 所以我们需要用create_graph=True 不然 这里计算图就清零了. 所以我们的梯度是更新label generator 使得其生成的 label 来更新multi-task network  (loss1 + loss2) 后的 primary loss的结果最低. 所以是二阶导.

**Comment by fuzzydeep** [comment]
那请问这里怎么能够显示的表达出\theta_2的梯度是怎么求得的呢？是loss1.backward()后，\theta_1的梯度乘上上一步中\theta_2的梯度吗？

**Comment by lorenmt** [comment]
只要有create_graph=True 他的计算图在,就可以直接call optimiser.step 来计算..

**Comment by fuzzydeep** [comment]
确实是这样，但是我其实比较好奇如何能表达出来，就是计算图上的计算路径怎么能显示计算出来。如果确实没有办法表达出来，就当我没说hhh，谢谢您了:)

**Comment by lorenmt** [comment]
如果你要问解析解的话, 那会比较困难. 但也可以用 一阶导来估计.
你可以参看我另外一篇文章: https://arxiv.org/abs/2202.03091 也是类似的想法.

**Comment by fuzzydeep** [comment]
谢谢您！
我还有几个小问题：
1. create_graph是为了保持gradient的计算图，那么在autograd这一步，\theta_2虽然加入了计算图，但并没有被计算梯度。那么这一步为什么\theta_2还能有gradient被保存在计算图中，以至于到loss1.backward()这一步被计算呢？
2. 我读了您的另外一篇文章后，尝试对这一过程推导了一下，您能帮忙检查一下吗？ps, 我尽量保持了和代码中的标号一致，L_1=train_loss1, L_2=train_loss2, L_pri是第二次梯度更新时的train_loss1。
![image](https://user-images.githubusercontent.com/70578961/178463697-6f2b0983-b1ec-4e55-bb8e-6ff1c65cdb02.png)

**Comment by lorenmt** [comment]
1. 我们保存是计算图，只有call loss1.backforward()的时候才算算到梯度。
2. 看上去应该是对的，只是你需要把 theta^+ 改成theta_1^'. 在MAXL里没有theat^+这个概念

**Comment by fuzzydeep** [comment]
嗯嗯 是的。其实从这个结果上看还挺直观的。第二次梯度下降时，第二行的第一项为0，所以只需要loss1.backward()即可。
再次谢谢您！
