### ISSUE TITLE
Why do you  add cos_mean between grad_1 and grad_2 to the total loss?

### ISSUE THREAD

**Issue by puhan123** [lorenmt/maxl#8]
Hi, I am interested in this job of yours but I have one question about the cos_mean between grad_1 and grad_2. I notice that you add the cos_mean between grad_1 and grad_2 to the loss.

 In your paper, you have denoted that, a cosine similarity of -1 indicates that the auxiliary labels work against the primary task. A cosine similarity of 0 indicates that the auxiliary labels have no impact on the primary task. And a cosine similarity of 1 indicates that the auxiliary labels are learning the same features as the primary task.

In this way, if you add cos_mean between grad_1 and grad_2 to the total loss, the learning of the model will tend to  minimise the cos_mean, however, the cos_mean is not the smaller the better. Therefore, why did you do that? 

Thank you very much.

![image](https://user-images.githubusercontent.com/24897773/196592810-b4353ca7-5d55-4822-b707-7c76ef6e25db.png)

**Comment by lorenmt** [comment]
Cosine similarity was not added to the loss. It was computed and stored in the "cost tensor" just for the purpose of visualisation.
